# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/Qt/Tools/CMake/bin/cmake

# The command to remove a file.
RM = /opt/Qt/Tools/CMake/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gabriele/Scrivania/Eta-louncer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gabriele/Scrivania/Eta-louncer/build/Desktop_Qt_6_12_0_Debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/Qt/Tools/CMake/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/Qt/Tools/CMake/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriele/Scrivania/Eta-louncer/build/Desktop_Qt_6_12_0_Debug/CMakeFiles /home/gabriele/Scrivania/Eta-louncer/build/Desktop_Qt_6_12_0_Debug//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gabriele/Scrivania/Eta-louncer/build/Desktop_Qt_6_12_0_Debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ETALauncher

# Build rule for target.
ETALauncher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ETALauncher
.PHONY : ETALauncher

# fast build rule for target.
ETALauncher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/build
.PHONY : ETALauncher/fast

#=============================================================================
# Target rules for targets named ETALauncher_autogen_timestamp_deps

# Build rule for target.
ETALauncher_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ETALauncher_autogen_timestamp_deps
.PHONY : ETALauncher_autogen_timestamp_deps

# fast build rule for target.
ETALauncher_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher_autogen_timestamp_deps.dir/build.make CMakeFiles/ETALauncher_autogen_timestamp_deps.dir/build
.PHONY : ETALauncher_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ETALauncher_autogen

# Build rule for target.
ETALauncher_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ETALauncher_autogen
.PHONY : ETALauncher_autogen

# fast build rule for target.
ETALauncher_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher_autogen.dir/build.make CMakeFiles/ETALauncher_autogen.dir/build
.PHONY : ETALauncher_autogen/fast

ETALauncher_autogen/EWIEGA46WW/qrc_resources.o: ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.o

# target to build an object file
ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.o

ETALauncher_autogen/EWIEGA46WW/qrc_resources.i: ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i

ETALauncher_autogen/EWIEGA46WW/qrc_resources.s: ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s

ETALauncher_autogen/mocs_compilation.o: ETALauncher_autogen/mocs_compilation.cpp.o
.PHONY : ETALauncher_autogen/mocs_compilation.o

# target to build an object file
ETALauncher_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/mocs_compilation.cpp.o
.PHONY : ETALauncher_autogen/mocs_compilation.cpp.o

ETALauncher_autogen/mocs_compilation.i: ETALauncher_autogen/mocs_compilation.cpp.i
.PHONY : ETALauncher_autogen/mocs_compilation.i

# target to preprocess a source file
ETALauncher_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/mocs_compilation.cpp.i
.PHONY : ETALauncher_autogen/mocs_compilation.cpp.i

ETALauncher_autogen/mocs_compilation.s: ETALauncher_autogen/mocs_compilation.cpp.s
.PHONY : ETALauncher_autogen/mocs_compilation.s

# target to generate assembly for a file
ETALauncher_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/mocs_compilation.cpp.s
.PHONY : ETALauncher_autogen/mocs_compilation.cpp.s

src/core/AuthManager.o: src/core/AuthManager.cpp.o
.PHONY : src/core/AuthManager.o

# target to build an object file
src/core/AuthManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/AuthManager.cpp.o
.PHONY : src/core/AuthManager.cpp.o

src/core/AuthManager.i: src/core/AuthManager.cpp.i
.PHONY : src/core/AuthManager.i

# target to preprocess a source file
src/core/AuthManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/AuthManager.cpp.i
.PHONY : src/core/AuthManager.cpp.i

src/core/AuthManager.s: src/core/AuthManager.cpp.s
.PHONY : src/core/AuthManager.s

# target to generate assembly for a file
src/core/AuthManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/AuthManager.cpp.s
.PHONY : src/core/AuthManager.cpp.s

src/core/BroadcastManager.o: src/core/BroadcastManager.cpp.o
.PHONY : src/core/BroadcastManager.o

# target to build an object file
src/core/BroadcastManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/BroadcastManager.cpp.o
.PHONY : src/core/BroadcastManager.cpp.o

src/core/BroadcastManager.i: src/core/BroadcastManager.cpp.i
.PHONY : src/core/BroadcastManager.i

# target to preprocess a source file
src/core/BroadcastManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/BroadcastManager.cpp.i
.PHONY : src/core/BroadcastManager.cpp.i

src/core/BroadcastManager.s: src/core/BroadcastManager.cpp.s
.PHONY : src/core/BroadcastManager.s

# target to generate assembly for a file
src/core/BroadcastManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/BroadcastManager.cpp.s
.PHONY : src/core/BroadcastManager.cpp.s

src/core/Config.o: src/core/Config.cpp.o
.PHONY : src/core/Config.o

# target to build an object file
src/core/Config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/Config.cpp.o
.PHONY : src/core/Config.cpp.o

src/core/Config.i: src/core/Config.cpp.i
.PHONY : src/core/Config.i

# target to preprocess a source file
src/core/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/Config.cpp.i
.PHONY : src/core/Config.cpp.i

src/core/Config.s: src/core/Config.cpp.s
.PHONY : src/core/Config.s

# target to generate assembly for a file
src/core/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/Config.cpp.s
.PHONY : src/core/Config.cpp.s

src/core/FirestoreClient.o: src/core/FirestoreClient.cpp.o
.PHONY : src/core/FirestoreClient.o

# target to build an object file
src/core/FirestoreClient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/FirestoreClient.cpp.o
.PHONY : src/core/FirestoreClient.cpp.o

src/core/FirestoreClient.i: src/core/FirestoreClient.cpp.i
.PHONY : src/core/FirestoreClient.i

# target to preprocess a source file
src/core/FirestoreClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/FirestoreClient.cpp.i
.PHONY : src/core/FirestoreClient.cpp.i

src/core/FirestoreClient.s: src/core/FirestoreClient.cpp.s
.PHONY : src/core/FirestoreClient.s

# target to generate assembly for a file
src/core/FirestoreClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/FirestoreClient.cpp.s
.PHONY : src/core/FirestoreClient.cpp.s

src/core/FriendsManager.o: src/core/FriendsManager.cpp.o
.PHONY : src/core/FriendsManager.o

# target to build an object file
src/core/FriendsManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/FriendsManager.cpp.o
.PHONY : src/core/FriendsManager.cpp.o

src/core/FriendsManager.i: src/core/FriendsManager.cpp.i
.PHONY : src/core/FriendsManager.i

# target to preprocess a source file
src/core/FriendsManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/FriendsManager.cpp.i
.PHONY : src/core/FriendsManager.cpp.i

src/core/FriendsManager.s: src/core/FriendsManager.cpp.s
.PHONY : src/core/FriendsManager.s

# target to generate assembly for a file
src/core/FriendsManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/FriendsManager.cpp.s
.PHONY : src/core/FriendsManager.cpp.s

src/core/GameManager.o: src/core/GameManager.cpp.o
.PHONY : src/core/GameManager.o

# target to build an object file
src/core/GameManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/GameManager.cpp.o
.PHONY : src/core/GameManager.cpp.o

src/core/GameManager.i: src/core/GameManager.cpp.i
.PHONY : src/core/GameManager.i

# target to preprocess a source file
src/core/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/GameManager.cpp.i
.PHONY : src/core/GameManager.cpp.i

src/core/GameManager.s: src/core/GameManager.cpp.s
.PHONY : src/core/GameManager.s

# target to generate assembly for a file
src/core/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/GameManager.cpp.s
.PHONY : src/core/GameManager.cpp.s

src/core/GitCloner.o: src/core/GitCloner.cpp.o
.PHONY : src/core/GitCloner.o

# target to build an object file
src/core/GitCloner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/GitCloner.cpp.o
.PHONY : src/core/GitCloner.cpp.o

src/core/GitCloner.i: src/core/GitCloner.cpp.i
.PHONY : src/core/GitCloner.i

# target to preprocess a source file
src/core/GitCloner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/GitCloner.cpp.i
.PHONY : src/core/GitCloner.cpp.i

src/core/GitCloner.s: src/core/GitCloner.cpp.s
.PHONY : src/core/GitCloner.s

# target to generate assembly for a file
src/core/GitCloner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/GitCloner.cpp.s
.PHONY : src/core/GitCloner.cpp.s

src/core/I18n.o: src/core/I18n.cpp.o
.PHONY : src/core/I18n.o

# target to build an object file
src/core/I18n.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/I18n.cpp.o
.PHONY : src/core/I18n.cpp.o

src/core/I18n.i: src/core/I18n.cpp.i
.PHONY : src/core/I18n.i

# target to preprocess a source file
src/core/I18n.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/I18n.cpp.i
.PHONY : src/core/I18n.cpp.i

src/core/I18n.s: src/core/I18n.cpp.s
.PHONY : src/core/I18n.s

# target to generate assembly for a file
src/core/I18n.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/I18n.cpp.s
.PHONY : src/core/I18n.cpp.s

src/core/PlayStats.o: src/core/PlayStats.cpp.o
.PHONY : src/core/PlayStats.o

# target to build an object file
src/core/PlayStats.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/PlayStats.cpp.o
.PHONY : src/core/PlayStats.cpp.o

src/core/PlayStats.i: src/core/PlayStats.cpp.i
.PHONY : src/core/PlayStats.i

# target to preprocess a source file
src/core/PlayStats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/PlayStats.cpp.i
.PHONY : src/core/PlayStats.cpp.i

src/core/PlayStats.s: src/core/PlayStats.cpp.s
.PHONY : src/core/PlayStats.s

# target to generate assembly for a file
src/core/PlayStats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/PlayStats.cpp.s
.PHONY : src/core/PlayStats.cpp.s

src/core/PresenceManager.o: src/core/PresenceManager.cpp.o
.PHONY : src/core/PresenceManager.o

# target to build an object file
src/core/PresenceManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/PresenceManager.cpp.o
.PHONY : src/core/PresenceManager.cpp.o

src/core/PresenceManager.i: src/core/PresenceManager.cpp.i
.PHONY : src/core/PresenceManager.i

# target to preprocess a source file
src/core/PresenceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/PresenceManager.cpp.i
.PHONY : src/core/PresenceManager.cpp.i

src/core/PresenceManager.s: src/core/PresenceManager.cpp.s
.PHONY : src/core/PresenceManager.s

# target to generate assembly for a file
src/core/PresenceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/PresenceManager.cpp.s
.PHONY : src/core/PresenceManager.cpp.s

src/core/RepoUpdater.o: src/core/RepoUpdater.cpp.o
.PHONY : src/core/RepoUpdater.o

# target to build an object file
src/core/RepoUpdater.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/RepoUpdater.cpp.o
.PHONY : src/core/RepoUpdater.cpp.o

src/core/RepoUpdater.i: src/core/RepoUpdater.cpp.i
.PHONY : src/core/RepoUpdater.i

# target to preprocess a source file
src/core/RepoUpdater.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/RepoUpdater.cpp.i
.PHONY : src/core/RepoUpdater.cpp.i

src/core/RepoUpdater.s: src/core/RepoUpdater.cpp.s
.PHONY : src/core/RepoUpdater.s

# target to generate assembly for a file
src/core/RepoUpdater.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/RepoUpdater.cpp.s
.PHONY : src/core/RepoUpdater.cpp.s

src/core/SelfUpdater.o: src/core/SelfUpdater.cpp.o
.PHONY : src/core/SelfUpdater.o

# target to build an object file
src/core/SelfUpdater.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/SelfUpdater.cpp.o
.PHONY : src/core/SelfUpdater.cpp.o

src/core/SelfUpdater.i: src/core/SelfUpdater.cpp.i
.PHONY : src/core/SelfUpdater.i

# target to preprocess a source file
src/core/SelfUpdater.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/SelfUpdater.cpp.i
.PHONY : src/core/SelfUpdater.cpp.i

src/core/SelfUpdater.s: src/core/SelfUpdater.cpp.s
.PHONY : src/core/SelfUpdater.s

# target to generate assembly for a file
src/core/SelfUpdater.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/SelfUpdater.cpp.s
.PHONY : src/core/SelfUpdater.cpp.s

src/core/SessionStore.o: src/core/SessionStore.cpp.o
.PHONY : src/core/SessionStore.o

# target to build an object file
src/core/SessionStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/SessionStore.cpp.o
.PHONY : src/core/SessionStore.cpp.o

src/core/SessionStore.i: src/core/SessionStore.cpp.i
.PHONY : src/core/SessionStore.i

# target to preprocess a source file
src/core/SessionStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/SessionStore.cpp.i
.PHONY : src/core/SessionStore.cpp.i

src/core/SessionStore.s: src/core/SessionStore.cpp.s
.PHONY : src/core/SessionStore.s

# target to generate assembly for a file
src/core/SessionStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/SessionStore.cpp.s
.PHONY : src/core/SessionStore.cpp.s

src/core/ShortcutManager.o: src/core/ShortcutManager.cpp.o
.PHONY : src/core/ShortcutManager.o

# target to build an object file
src/core/ShortcutManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/ShortcutManager.cpp.o
.PHONY : src/core/ShortcutManager.cpp.o

src/core/ShortcutManager.i: src/core/ShortcutManager.cpp.i
.PHONY : src/core/ShortcutManager.i

# target to preprocess a source file
src/core/ShortcutManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/ShortcutManager.cpp.i
.PHONY : src/core/ShortcutManager.cpp.i

src/core/ShortcutManager.s: src/core/ShortcutManager.cpp.s
.PHONY : src/core/ShortcutManager.s

# target to generate assembly for a file
src/core/ShortcutManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/ShortcutManager.cpp.s
.PHONY : src/core/ShortcutManager.cpp.s

src/core/ThemeManager.o: src/core/ThemeManager.cpp.o
.PHONY : src/core/ThemeManager.o

# target to build an object file
src/core/ThemeManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/ThemeManager.cpp.o
.PHONY : src/core/ThemeManager.cpp.o

src/core/ThemeManager.i: src/core/ThemeManager.cpp.i
.PHONY : src/core/ThemeManager.i

# target to preprocess a source file
src/core/ThemeManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/ThemeManager.cpp.i
.PHONY : src/core/ThemeManager.cpp.i

src/core/ThemeManager.s: src/core/ThemeManager.cpp.s
.PHONY : src/core/ThemeManager.s

# target to generate assembly for a file
src/core/ThemeManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/ThemeManager.cpp.s
.PHONY : src/core/ThemeManager.cpp.s

src/core/Translations.o: src/core/Translations.cpp.o
.PHONY : src/core/Translations.o

# target to build an object file
src/core/Translations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/Translations.cpp.o
.PHONY : src/core/Translations.cpp.o

src/core/Translations.i: src/core/Translations.cpp.i
.PHONY : src/core/Translations.i

# target to preprocess a source file
src/core/Translations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/Translations.cpp.i
.PHONY : src/core/Translations.cpp.i

src/core/Translations.s: src/core/Translations.cpp.s
.PHONY : src/core/Translations.s

# target to generate assembly for a file
src/core/Translations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/Translations.cpp.s
.PHONY : src/core/Translations.cpp.s

src/core/UpdateChecker.o: src/core/UpdateChecker.cpp.o
.PHONY : src/core/UpdateChecker.o

# target to build an object file
src/core/UpdateChecker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/UpdateChecker.cpp.o
.PHONY : src/core/UpdateChecker.cpp.o

src/core/UpdateChecker.i: src/core/UpdateChecker.cpp.i
.PHONY : src/core/UpdateChecker.i

# target to preprocess a source file
src/core/UpdateChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/UpdateChecker.cpp.i
.PHONY : src/core/UpdateChecker.cpp.i

src/core/UpdateChecker.s: src/core/UpdateChecker.cpp.s
.PHONY : src/core/UpdateChecker.s

# target to generate assembly for a file
src/core/UpdateChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/core/UpdateChecker.cpp.s
.PHONY : src/core/UpdateChecker.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/BroadcastWidget.o: src/ui/BroadcastWidget.cpp.o
.PHONY : src/ui/BroadcastWidget.o

# target to build an object file
src/ui/BroadcastWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/BroadcastWidget.cpp.o
.PHONY : src/ui/BroadcastWidget.cpp.o

src/ui/BroadcastWidget.i: src/ui/BroadcastWidget.cpp.i
.PHONY : src/ui/BroadcastWidget.i

# target to preprocess a source file
src/ui/BroadcastWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/BroadcastWidget.cpp.i
.PHONY : src/ui/BroadcastWidget.cpp.i

src/ui/BroadcastWidget.s: src/ui/BroadcastWidget.cpp.s
.PHONY : src/ui/BroadcastWidget.s

# target to generate assembly for a file
src/ui/BroadcastWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/BroadcastWidget.cpp.s
.PHONY : src/ui/BroadcastWidget.cpp.s

src/ui/ChangelogDialog.o: src/ui/ChangelogDialog.cpp.o
.PHONY : src/ui/ChangelogDialog.o

# target to build an object file
src/ui/ChangelogDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ChangelogDialog.cpp.o
.PHONY : src/ui/ChangelogDialog.cpp.o

src/ui/ChangelogDialog.i: src/ui/ChangelogDialog.cpp.i
.PHONY : src/ui/ChangelogDialog.i

# target to preprocess a source file
src/ui/ChangelogDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ChangelogDialog.cpp.i
.PHONY : src/ui/ChangelogDialog.cpp.i

src/ui/ChangelogDialog.s: src/ui/ChangelogDialog.cpp.s
.PHONY : src/ui/ChangelogDialog.s

# target to generate assembly for a file
src/ui/ChangelogDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ChangelogDialog.cpp.s
.PHONY : src/ui/ChangelogDialog.cpp.s

src/ui/FriendsWidget.o: src/ui/FriendsWidget.cpp.o
.PHONY : src/ui/FriendsWidget.o

# target to build an object file
src/ui/FriendsWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/FriendsWidget.cpp.o
.PHONY : src/ui/FriendsWidget.cpp.o

src/ui/FriendsWidget.i: src/ui/FriendsWidget.cpp.i
.PHONY : src/ui/FriendsWidget.i

# target to preprocess a source file
src/ui/FriendsWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/FriendsWidget.cpp.i
.PHONY : src/ui/FriendsWidget.cpp.i

src/ui/FriendsWidget.s: src/ui/FriendsWidget.cpp.s
.PHONY : src/ui/FriendsWidget.s

# target to generate assembly for a file
src/ui/FriendsWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/FriendsWidget.cpp.s
.PHONY : src/ui/FriendsWidget.cpp.s

src/ui/GameCardWidget.o: src/ui/GameCardWidget.cpp.o
.PHONY : src/ui/GameCardWidget.o

# target to build an object file
src/ui/GameCardWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/GameCardWidget.cpp.o
.PHONY : src/ui/GameCardWidget.cpp.o

src/ui/GameCardWidget.i: src/ui/GameCardWidget.cpp.i
.PHONY : src/ui/GameCardWidget.i

# target to preprocess a source file
src/ui/GameCardWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/GameCardWidget.cpp.i
.PHONY : src/ui/GameCardWidget.cpp.i

src/ui/GameCardWidget.s: src/ui/GameCardWidget.cpp.s
.PHONY : src/ui/GameCardWidget.s

# target to generate assembly for a file
src/ui/GameCardWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/GameCardWidget.cpp.s
.PHONY : src/ui/GameCardWidget.cpp.s

src/ui/InstallProgressDialog.o: src/ui/InstallProgressDialog.cpp.o
.PHONY : src/ui/InstallProgressDialog.o

# target to build an object file
src/ui/InstallProgressDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/InstallProgressDialog.cpp.o
.PHONY : src/ui/InstallProgressDialog.cpp.o

src/ui/InstallProgressDialog.i: src/ui/InstallProgressDialog.cpp.i
.PHONY : src/ui/InstallProgressDialog.i

# target to preprocess a source file
src/ui/InstallProgressDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/InstallProgressDialog.cpp.i
.PHONY : src/ui/InstallProgressDialog.cpp.i

src/ui/InstallProgressDialog.s: src/ui/InstallProgressDialog.cpp.s
.PHONY : src/ui/InstallProgressDialog.s

# target to generate assembly for a file
src/ui/InstallProgressDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/InstallProgressDialog.cpp.s
.PHONY : src/ui/InstallProgressDialog.cpp.s

src/ui/LoginWidget.o: src/ui/LoginWidget.cpp.o
.PHONY : src/ui/LoginWidget.o

# target to build an object file
src/ui/LoginWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/LoginWidget.cpp.o
.PHONY : src/ui/LoginWidget.cpp.o

src/ui/LoginWidget.i: src/ui/LoginWidget.cpp.i
.PHONY : src/ui/LoginWidget.i

# target to preprocess a source file
src/ui/LoginWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/LoginWidget.cpp.i
.PHONY : src/ui/LoginWidget.cpp.i

src/ui/LoginWidget.s: src/ui/LoginWidget.cpp.s
.PHONY : src/ui/LoginWidget.s

# target to generate assembly for a file
src/ui/LoginWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/LoginWidget.cpp.s
.PHONY : src/ui/LoginWidget.cpp.s

src/ui/MainWindow.o: src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.o

# target to build an object file
src/ui/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/MainWindow.cpp.o
.PHONY : src/ui/MainWindow.cpp.o

src/ui/MainWindow.i: src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.i

# target to preprocess a source file
src/ui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.cpp.i

src/ui/MainWindow.s: src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.s

# target to generate assembly for a file
src/ui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.cpp.s

src/ui/ManageDialog.o: src/ui/ManageDialog.cpp.o
.PHONY : src/ui/ManageDialog.o

# target to build an object file
src/ui/ManageDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ManageDialog.cpp.o
.PHONY : src/ui/ManageDialog.cpp.o

src/ui/ManageDialog.i: src/ui/ManageDialog.cpp.i
.PHONY : src/ui/ManageDialog.i

# target to preprocess a source file
src/ui/ManageDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ManageDialog.cpp.i
.PHONY : src/ui/ManageDialog.cpp.i

src/ui/ManageDialog.s: src/ui/ManageDialog.cpp.s
.PHONY : src/ui/ManageDialog.s

# target to generate assembly for a file
src/ui/ManageDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ManageDialog.cpp.s
.PHONY : src/ui/ManageDialog.cpp.s

src/ui/ProfileWidget.o: src/ui/ProfileWidget.cpp.o
.PHONY : src/ui/ProfileWidget.o

# target to build an object file
src/ui/ProfileWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ProfileWidget.cpp.o
.PHONY : src/ui/ProfileWidget.cpp.o

src/ui/ProfileWidget.i: src/ui/ProfileWidget.cpp.i
.PHONY : src/ui/ProfileWidget.i

# target to preprocess a source file
src/ui/ProfileWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ProfileWidget.cpp.i
.PHONY : src/ui/ProfileWidget.cpp.i

src/ui/ProfileWidget.s: src/ui/ProfileWidget.cpp.s
.PHONY : src/ui/ProfileWidget.s

# target to generate assembly for a file
src/ui/ProfileWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ProfileWidget.cpp.s
.PHONY : src/ui/ProfileWidget.cpp.s

src/ui/ReviewsDialog.o: src/ui/ReviewsDialog.cpp.o
.PHONY : src/ui/ReviewsDialog.o

# target to build an object file
src/ui/ReviewsDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ReviewsDialog.cpp.o
.PHONY : src/ui/ReviewsDialog.cpp.o

src/ui/ReviewsDialog.i: src/ui/ReviewsDialog.cpp.i
.PHONY : src/ui/ReviewsDialog.i

# target to preprocess a source file
src/ui/ReviewsDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ReviewsDialog.cpp.i
.PHONY : src/ui/ReviewsDialog.cpp.i

src/ui/ReviewsDialog.s: src/ui/ReviewsDialog.cpp.s
.PHONY : src/ui/ReviewsDialog.s

# target to generate assembly for a file
src/ui/ReviewsDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ReviewsDialog.cpp.s
.PHONY : src/ui/ReviewsDialog.cpp.s

src/ui/SettingsDialog.o: src/ui/SettingsDialog.cpp.o
.PHONY : src/ui/SettingsDialog.o

# target to build an object file
src/ui/SettingsDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/SettingsDialog.cpp.o
.PHONY : src/ui/SettingsDialog.cpp.o

src/ui/SettingsDialog.i: src/ui/SettingsDialog.cpp.i
.PHONY : src/ui/SettingsDialog.i

# target to preprocess a source file
src/ui/SettingsDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/SettingsDialog.cpp.i
.PHONY : src/ui/SettingsDialog.cpp.i

src/ui/SettingsDialog.s: src/ui/SettingsDialog.cpp.s
.PHONY : src/ui/SettingsDialog.s

# target to generate assembly for a file
src/ui/SettingsDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/SettingsDialog.cpp.s
.PHONY : src/ui/SettingsDialog.cpp.s

src/ui/StatsWidget.o: src/ui/StatsWidget.cpp.o
.PHONY : src/ui/StatsWidget.o

# target to build an object file
src/ui/StatsWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/StatsWidget.cpp.o
.PHONY : src/ui/StatsWidget.cpp.o

src/ui/StatsWidget.i: src/ui/StatsWidget.cpp.i
.PHONY : src/ui/StatsWidget.i

# target to preprocess a source file
src/ui/StatsWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/StatsWidget.cpp.i
.PHONY : src/ui/StatsWidget.cpp.i

src/ui/StatsWidget.s: src/ui/StatsWidget.cpp.s
.PHONY : src/ui/StatsWidget.s

# target to generate assembly for a file
src/ui/StatsWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/StatsWidget.cpp.s
.PHONY : src/ui/StatsWidget.cpp.s

src/ui/ToggleSwitch.o: src/ui/ToggleSwitch.cpp.o
.PHONY : src/ui/ToggleSwitch.o

# target to build an object file
src/ui/ToggleSwitch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ToggleSwitch.cpp.o
.PHONY : src/ui/ToggleSwitch.cpp.o

src/ui/ToggleSwitch.i: src/ui/ToggleSwitch.cpp.i
.PHONY : src/ui/ToggleSwitch.i

# target to preprocess a source file
src/ui/ToggleSwitch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ToggleSwitch.cpp.i
.PHONY : src/ui/ToggleSwitch.cpp.i

src/ui/ToggleSwitch.s: src/ui/ToggleSwitch.cpp.s
.PHONY : src/ui/ToggleSwitch.s

# target to generate assembly for a file
src/ui/ToggleSwitch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/ToggleSwitch.cpp.s
.PHONY : src/ui/ToggleSwitch.cpp.s

src/ui/TrayController.o: src/ui/TrayController.cpp.o
.PHONY : src/ui/TrayController.o

# target to build an object file
src/ui/TrayController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/TrayController.cpp.o
.PHONY : src/ui/TrayController.cpp.o

src/ui/TrayController.i: src/ui/TrayController.cpp.i
.PHONY : src/ui/TrayController.i

# target to preprocess a source file
src/ui/TrayController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/TrayController.cpp.i
.PHONY : src/ui/TrayController.cpp.i

src/ui/TrayController.s: src/ui/TrayController.cpp.s
.PHONY : src/ui/TrayController.s

# target to generate assembly for a file
src/ui/TrayController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ETALauncher.dir/build.make CMakeFiles/ETALauncher.dir/src/ui/TrayController.cpp.s
.PHONY : src/ui/TrayController.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ETALauncher_autogen"
	@echo "... ETALauncher_autogen_timestamp_deps"
	@echo "... ETALauncher"
	@echo "... ETALauncher_autogen/EWIEGA46WW/qrc_resources.o"
	@echo "... ETALauncher_autogen/EWIEGA46WW/qrc_resources.i"
	@echo "... ETALauncher_autogen/EWIEGA46WW/qrc_resources.s"
	@echo "... ETALauncher_autogen/mocs_compilation.o"
	@echo "... ETALauncher_autogen/mocs_compilation.i"
	@echo "... ETALauncher_autogen/mocs_compilation.s"
	@echo "... src/core/AuthManager.o"
	@echo "... src/core/AuthManager.i"
	@echo "... src/core/AuthManager.s"
	@echo "... src/core/BroadcastManager.o"
	@echo "... src/core/BroadcastManager.i"
	@echo "... src/core/BroadcastManager.s"
	@echo "... src/core/Config.o"
	@echo "... src/core/Config.i"
	@echo "... src/core/Config.s"
	@echo "... src/core/FirestoreClient.o"
	@echo "... src/core/FirestoreClient.i"
	@echo "... src/core/FirestoreClient.s"
	@echo "... src/core/FriendsManager.o"
	@echo "... src/core/FriendsManager.i"
	@echo "... src/core/FriendsManager.s"
	@echo "... src/core/GameManager.o"
	@echo "... src/core/GameManager.i"
	@echo "... src/core/GameManager.s"
	@echo "... src/core/GitCloner.o"
	@echo "... src/core/GitCloner.i"
	@echo "... src/core/GitCloner.s"
	@echo "... src/core/I18n.o"
	@echo "... src/core/I18n.i"
	@echo "... src/core/I18n.s"
	@echo "... src/core/PlayStats.o"
	@echo "... src/core/PlayStats.i"
	@echo "... src/core/PlayStats.s"
	@echo "... src/core/PresenceManager.o"
	@echo "... src/core/PresenceManager.i"
	@echo "... src/core/PresenceManager.s"
	@echo "... src/core/RepoUpdater.o"
	@echo "... src/core/RepoUpdater.i"
	@echo "... src/core/RepoUpdater.s"
	@echo "... src/core/SelfUpdater.o"
	@echo "... src/core/SelfUpdater.i"
	@echo "... src/core/SelfUpdater.s"
	@echo "... src/core/SessionStore.o"
	@echo "... src/core/SessionStore.i"
	@echo "... src/core/SessionStore.s"
	@echo "... src/core/ShortcutManager.o"
	@echo "... src/core/ShortcutManager.i"
	@echo "... src/core/ShortcutManager.s"
	@echo "... src/core/ThemeManager.o"
	@echo "... src/core/ThemeManager.i"
	@echo "... src/core/ThemeManager.s"
	@echo "... src/core/Translations.o"
	@echo "... src/core/Translations.i"
	@echo "... src/core/Translations.s"
	@echo "... src/core/UpdateChecker.o"
	@echo "... src/core/UpdateChecker.i"
	@echo "... src/core/UpdateChecker.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ui/BroadcastWidget.o"
	@echo "... src/ui/BroadcastWidget.i"
	@echo "... src/ui/BroadcastWidget.s"
	@echo "... src/ui/ChangelogDialog.o"
	@echo "... src/ui/ChangelogDialog.i"
	@echo "... src/ui/ChangelogDialog.s"
	@echo "... src/ui/FriendsWidget.o"
	@echo "... src/ui/FriendsWidget.i"
	@echo "... src/ui/FriendsWidget.s"
	@echo "... src/ui/GameCardWidget.o"
	@echo "... src/ui/GameCardWidget.i"
	@echo "... src/ui/GameCardWidget.s"
	@echo "... src/ui/InstallProgressDialog.o"
	@echo "... src/ui/InstallProgressDialog.i"
	@echo "... src/ui/InstallProgressDialog.s"
	@echo "... src/ui/LoginWidget.o"
	@echo "... src/ui/LoginWidget.i"
	@echo "... src/ui/LoginWidget.s"
	@echo "... src/ui/MainWindow.o"
	@echo "... src/ui/MainWindow.i"
	@echo "... src/ui/MainWindow.s"
	@echo "... src/ui/ManageDialog.o"
	@echo "... src/ui/ManageDialog.i"
	@echo "... src/ui/ManageDialog.s"
	@echo "... src/ui/ProfileWidget.o"
	@echo "... src/ui/ProfileWidget.i"
	@echo "... src/ui/ProfileWidget.s"
	@echo "... src/ui/ReviewsDialog.o"
	@echo "... src/ui/ReviewsDialog.i"
	@echo "... src/ui/ReviewsDialog.s"
	@echo "... src/ui/SettingsDialog.o"
	@echo "... src/ui/SettingsDialog.i"
	@echo "... src/ui/SettingsDialog.s"
	@echo "... src/ui/StatsWidget.o"
	@echo "... src/ui/StatsWidget.i"
	@echo "... src/ui/StatsWidget.s"
	@echo "... src/ui/ToggleSwitch.o"
	@echo "... src/ui/ToggleSwitch.i"
	@echo "... src/ui/ToggleSwitch.s"
	@echo "... src/ui/TrayController.o"
	@echo "... src/ui/TrayController.i"
	@echo "... src/ui/TrayController.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

