# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\Qt\Tools\CMake_64\bin\cmake.exe

# The command to remove a file.
RM = C:\Qt\Tools\CMake_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\gabri\Documents\eta-launcher-cpp\Eta-louncer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\gabri\Documents\eta-launcher-cpp\Eta-louncer\build\Desktop_Qt_6_12_0_MinGW_64_bit_Debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	C:\Qt\Tools\CMake_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\Qt\Tools\CMake_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\gabri\Documents\eta-launcher-cpp\Eta-louncer\build\Desktop_Qt_6_12_0_MinGW_64_bit_Debug\CMakeFiles C:\Users\gabri\Documents\eta-launcher-cpp\Eta-louncer\build\Desktop_Qt_6_12_0_MinGW_64_bit_Debug\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\gabri\Documents\eta-launcher-cpp\Eta-louncer\build\Desktop_Qt_6_12_0_MinGW_64_bit_Debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ETALauncher

# Build rule for target.
ETALauncher: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ETALauncher
.PHONY : ETALauncher

# fast build rule for target.
ETALauncher/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/build
.PHONY : ETALauncher/fast

#=============================================================================
# Target rules for targets named ETALauncher_autogen_timestamp_deps

# Build rule for target.
ETALauncher_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ETALauncher_autogen_timestamp_deps
.PHONY : ETALauncher_autogen_timestamp_deps

# fast build rule for target.
ETALauncher_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher_autogen_timestamp_deps.dir\build.make CMakeFiles/ETALauncher_autogen_timestamp_deps.dir/build
.PHONY : ETALauncher_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named ETALauncher_autogen

# Build rule for target.
ETALauncher_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ETALauncher_autogen
.PHONY : ETALauncher_autogen

# fast build rule for target.
ETALauncher_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher_autogen.dir\build.make CMakeFiles/ETALauncher_autogen.dir/build
.PHONY : ETALauncher_autogen/fast

ETALauncher_autogen/EWIEGA46WW/qrc_resources.obj: ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.obj
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.obj

# target to build an object file
ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.obj
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.obj

ETALauncher_autogen/EWIEGA46WW/qrc_resources.i: ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.i

ETALauncher_autogen/EWIEGA46WW/qrc_resources.s: ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : ETALauncher_autogen/EWIEGA46WW/qrc_resources.cpp.s

ETALauncher_autogen/mocs_compilation.obj: ETALauncher_autogen/mocs_compilation.cpp.obj
.PHONY : ETALauncher_autogen/mocs_compilation.obj

# target to build an object file
ETALauncher_autogen/mocs_compilation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/mocs_compilation.cpp.obj
.PHONY : ETALauncher_autogen/mocs_compilation.cpp.obj

ETALauncher_autogen/mocs_compilation.i: ETALauncher_autogen/mocs_compilation.cpp.i
.PHONY : ETALauncher_autogen/mocs_compilation.i

# target to preprocess a source file
ETALauncher_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/mocs_compilation.cpp.i
.PHONY : ETALauncher_autogen/mocs_compilation.cpp.i

ETALauncher_autogen/mocs_compilation.s: ETALauncher_autogen/mocs_compilation.cpp.s
.PHONY : ETALauncher_autogen/mocs_compilation.s

# target to generate assembly for a file
ETALauncher_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/ETALauncher_autogen/mocs_compilation.cpp.s
.PHONY : ETALauncher_autogen/mocs_compilation.cpp.s

src/core/AuthManager.obj: src/core/AuthManager.cpp.obj
.PHONY : src/core/AuthManager.obj

# target to build an object file
src/core/AuthManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/AuthManager.cpp.obj
.PHONY : src/core/AuthManager.cpp.obj

src/core/AuthManager.i: src/core/AuthManager.cpp.i
.PHONY : src/core/AuthManager.i

# target to preprocess a source file
src/core/AuthManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/AuthManager.cpp.i
.PHONY : src/core/AuthManager.cpp.i

src/core/AuthManager.s: src/core/AuthManager.cpp.s
.PHONY : src/core/AuthManager.s

# target to generate assembly for a file
src/core/AuthManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/AuthManager.cpp.s
.PHONY : src/core/AuthManager.cpp.s

src/core/BroadcastManager.obj: src/core/BroadcastManager.cpp.obj
.PHONY : src/core/BroadcastManager.obj

# target to build an object file
src/core/BroadcastManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/BroadcastManager.cpp.obj
.PHONY : src/core/BroadcastManager.cpp.obj

src/core/BroadcastManager.i: src/core/BroadcastManager.cpp.i
.PHONY : src/core/BroadcastManager.i

# target to preprocess a source file
src/core/BroadcastManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/BroadcastManager.cpp.i
.PHONY : src/core/BroadcastManager.cpp.i

src/core/BroadcastManager.s: src/core/BroadcastManager.cpp.s
.PHONY : src/core/BroadcastManager.s

# target to generate assembly for a file
src/core/BroadcastManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/BroadcastManager.cpp.s
.PHONY : src/core/BroadcastManager.cpp.s

src/core/Config.obj: src/core/Config.cpp.obj
.PHONY : src/core/Config.obj

# target to build an object file
src/core/Config.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/Config.cpp.obj
.PHONY : src/core/Config.cpp.obj

src/core/Config.i: src/core/Config.cpp.i
.PHONY : src/core/Config.i

# target to preprocess a source file
src/core/Config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/Config.cpp.i
.PHONY : src/core/Config.cpp.i

src/core/Config.s: src/core/Config.cpp.s
.PHONY : src/core/Config.s

# target to generate assembly for a file
src/core/Config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/Config.cpp.s
.PHONY : src/core/Config.cpp.s

src/core/FirestoreClient.obj: src/core/FirestoreClient.cpp.obj
.PHONY : src/core/FirestoreClient.obj

# target to build an object file
src/core/FirestoreClient.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/FirestoreClient.cpp.obj
.PHONY : src/core/FirestoreClient.cpp.obj

src/core/FirestoreClient.i: src/core/FirestoreClient.cpp.i
.PHONY : src/core/FirestoreClient.i

# target to preprocess a source file
src/core/FirestoreClient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/FirestoreClient.cpp.i
.PHONY : src/core/FirestoreClient.cpp.i

src/core/FirestoreClient.s: src/core/FirestoreClient.cpp.s
.PHONY : src/core/FirestoreClient.s

# target to generate assembly for a file
src/core/FirestoreClient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/FirestoreClient.cpp.s
.PHONY : src/core/FirestoreClient.cpp.s

src/core/FriendsManager.obj: src/core/FriendsManager.cpp.obj
.PHONY : src/core/FriendsManager.obj

# target to build an object file
src/core/FriendsManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/FriendsManager.cpp.obj
.PHONY : src/core/FriendsManager.cpp.obj

src/core/FriendsManager.i: src/core/FriendsManager.cpp.i
.PHONY : src/core/FriendsManager.i

# target to preprocess a source file
src/core/FriendsManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/FriendsManager.cpp.i
.PHONY : src/core/FriendsManager.cpp.i

src/core/FriendsManager.s: src/core/FriendsManager.cpp.s
.PHONY : src/core/FriendsManager.s

# target to generate assembly for a file
src/core/FriendsManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/FriendsManager.cpp.s
.PHONY : src/core/FriendsManager.cpp.s

src/core/GameManager.obj: src/core/GameManager.cpp.obj
.PHONY : src/core/GameManager.obj

# target to build an object file
src/core/GameManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/GameManager.cpp.obj
.PHONY : src/core/GameManager.cpp.obj

src/core/GameManager.i: src/core/GameManager.cpp.i
.PHONY : src/core/GameManager.i

# target to preprocess a source file
src/core/GameManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/GameManager.cpp.i
.PHONY : src/core/GameManager.cpp.i

src/core/GameManager.s: src/core/GameManager.cpp.s
.PHONY : src/core/GameManager.s

# target to generate assembly for a file
src/core/GameManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/GameManager.cpp.s
.PHONY : src/core/GameManager.cpp.s

src/core/GitCloner.obj: src/core/GitCloner.cpp.obj
.PHONY : src/core/GitCloner.obj

# target to build an object file
src/core/GitCloner.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/GitCloner.cpp.obj
.PHONY : src/core/GitCloner.cpp.obj

src/core/GitCloner.i: src/core/GitCloner.cpp.i
.PHONY : src/core/GitCloner.i

# target to preprocess a source file
src/core/GitCloner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/GitCloner.cpp.i
.PHONY : src/core/GitCloner.cpp.i

src/core/GitCloner.s: src/core/GitCloner.cpp.s
.PHONY : src/core/GitCloner.s

# target to generate assembly for a file
src/core/GitCloner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/GitCloner.cpp.s
.PHONY : src/core/GitCloner.cpp.s

src/core/I18n.obj: src/core/I18n.cpp.obj
.PHONY : src/core/I18n.obj

# target to build an object file
src/core/I18n.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/I18n.cpp.obj
.PHONY : src/core/I18n.cpp.obj

src/core/I18n.i: src/core/I18n.cpp.i
.PHONY : src/core/I18n.i

# target to preprocess a source file
src/core/I18n.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/I18n.cpp.i
.PHONY : src/core/I18n.cpp.i

src/core/I18n.s: src/core/I18n.cpp.s
.PHONY : src/core/I18n.s

# target to generate assembly for a file
src/core/I18n.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/I18n.cpp.s
.PHONY : src/core/I18n.cpp.s

src/core/PlayStats.obj: src/core/PlayStats.cpp.obj
.PHONY : src/core/PlayStats.obj

# target to build an object file
src/core/PlayStats.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/PlayStats.cpp.obj
.PHONY : src/core/PlayStats.cpp.obj

src/core/PlayStats.i: src/core/PlayStats.cpp.i
.PHONY : src/core/PlayStats.i

# target to preprocess a source file
src/core/PlayStats.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/PlayStats.cpp.i
.PHONY : src/core/PlayStats.cpp.i

src/core/PlayStats.s: src/core/PlayStats.cpp.s
.PHONY : src/core/PlayStats.s

# target to generate assembly for a file
src/core/PlayStats.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/PlayStats.cpp.s
.PHONY : src/core/PlayStats.cpp.s

src/core/PresenceManager.obj: src/core/PresenceManager.cpp.obj
.PHONY : src/core/PresenceManager.obj

# target to build an object file
src/core/PresenceManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/PresenceManager.cpp.obj
.PHONY : src/core/PresenceManager.cpp.obj

src/core/PresenceManager.i: src/core/PresenceManager.cpp.i
.PHONY : src/core/PresenceManager.i

# target to preprocess a source file
src/core/PresenceManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/PresenceManager.cpp.i
.PHONY : src/core/PresenceManager.cpp.i

src/core/PresenceManager.s: src/core/PresenceManager.cpp.s
.PHONY : src/core/PresenceManager.s

# target to generate assembly for a file
src/core/PresenceManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/PresenceManager.cpp.s
.PHONY : src/core/PresenceManager.cpp.s

src/core/RepoUpdater.obj: src/core/RepoUpdater.cpp.obj
.PHONY : src/core/RepoUpdater.obj

# target to build an object file
src/core/RepoUpdater.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/RepoUpdater.cpp.obj
.PHONY : src/core/RepoUpdater.cpp.obj

src/core/RepoUpdater.i: src/core/RepoUpdater.cpp.i
.PHONY : src/core/RepoUpdater.i

# target to preprocess a source file
src/core/RepoUpdater.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/RepoUpdater.cpp.i
.PHONY : src/core/RepoUpdater.cpp.i

src/core/RepoUpdater.s: src/core/RepoUpdater.cpp.s
.PHONY : src/core/RepoUpdater.s

# target to generate assembly for a file
src/core/RepoUpdater.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/RepoUpdater.cpp.s
.PHONY : src/core/RepoUpdater.cpp.s

src/core/SelfUpdater.obj: src/core/SelfUpdater.cpp.obj
.PHONY : src/core/SelfUpdater.obj

# target to build an object file
src/core/SelfUpdater.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/SelfUpdater.cpp.obj
.PHONY : src/core/SelfUpdater.cpp.obj

src/core/SelfUpdater.i: src/core/SelfUpdater.cpp.i
.PHONY : src/core/SelfUpdater.i

# target to preprocess a source file
src/core/SelfUpdater.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/SelfUpdater.cpp.i
.PHONY : src/core/SelfUpdater.cpp.i

src/core/SelfUpdater.s: src/core/SelfUpdater.cpp.s
.PHONY : src/core/SelfUpdater.s

# target to generate assembly for a file
src/core/SelfUpdater.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/SelfUpdater.cpp.s
.PHONY : src/core/SelfUpdater.cpp.s

src/core/SessionStore.obj: src/core/SessionStore.cpp.obj
.PHONY : src/core/SessionStore.obj

# target to build an object file
src/core/SessionStore.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/SessionStore.cpp.obj
.PHONY : src/core/SessionStore.cpp.obj

src/core/SessionStore.i: src/core/SessionStore.cpp.i
.PHONY : src/core/SessionStore.i

# target to preprocess a source file
src/core/SessionStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/SessionStore.cpp.i
.PHONY : src/core/SessionStore.cpp.i

src/core/SessionStore.s: src/core/SessionStore.cpp.s
.PHONY : src/core/SessionStore.s

# target to generate assembly for a file
src/core/SessionStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/SessionStore.cpp.s
.PHONY : src/core/SessionStore.cpp.s

src/core/ShortcutManager.obj: src/core/ShortcutManager.cpp.obj
.PHONY : src/core/ShortcutManager.obj

# target to build an object file
src/core/ShortcutManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/ShortcutManager.cpp.obj
.PHONY : src/core/ShortcutManager.cpp.obj

src/core/ShortcutManager.i: src/core/ShortcutManager.cpp.i
.PHONY : src/core/ShortcutManager.i

# target to preprocess a source file
src/core/ShortcutManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/ShortcutManager.cpp.i
.PHONY : src/core/ShortcutManager.cpp.i

src/core/ShortcutManager.s: src/core/ShortcutManager.cpp.s
.PHONY : src/core/ShortcutManager.s

# target to generate assembly for a file
src/core/ShortcutManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/ShortcutManager.cpp.s
.PHONY : src/core/ShortcutManager.cpp.s

src/core/ThemeManager.obj: src/core/ThemeManager.cpp.obj
.PHONY : src/core/ThemeManager.obj

# target to build an object file
src/core/ThemeManager.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/ThemeManager.cpp.obj
.PHONY : src/core/ThemeManager.cpp.obj

src/core/ThemeManager.i: src/core/ThemeManager.cpp.i
.PHONY : src/core/ThemeManager.i

# target to preprocess a source file
src/core/ThemeManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/ThemeManager.cpp.i
.PHONY : src/core/ThemeManager.cpp.i

src/core/ThemeManager.s: src/core/ThemeManager.cpp.s
.PHONY : src/core/ThemeManager.s

# target to generate assembly for a file
src/core/ThemeManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/ThemeManager.cpp.s
.PHONY : src/core/ThemeManager.cpp.s

src/core/Translations.obj: src/core/Translations.cpp.obj
.PHONY : src/core/Translations.obj

# target to build an object file
src/core/Translations.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/Translations.cpp.obj
.PHONY : src/core/Translations.cpp.obj

src/core/Translations.i: src/core/Translations.cpp.i
.PHONY : src/core/Translations.i

# target to preprocess a source file
src/core/Translations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/Translations.cpp.i
.PHONY : src/core/Translations.cpp.i

src/core/Translations.s: src/core/Translations.cpp.s
.PHONY : src/core/Translations.s

# target to generate assembly for a file
src/core/Translations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/Translations.cpp.s
.PHONY : src/core/Translations.cpp.s

src/core/UpdateChecker.obj: src/core/UpdateChecker.cpp.obj
.PHONY : src/core/UpdateChecker.obj

# target to build an object file
src/core/UpdateChecker.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/UpdateChecker.cpp.obj
.PHONY : src/core/UpdateChecker.cpp.obj

src/core/UpdateChecker.i: src/core/UpdateChecker.cpp.i
.PHONY : src/core/UpdateChecker.i

# target to preprocess a source file
src/core/UpdateChecker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/UpdateChecker.cpp.i
.PHONY : src/core/UpdateChecker.cpp.i

src/core/UpdateChecker.s: src/core/UpdateChecker.cpp.s
.PHONY : src/core/UpdateChecker.s

# target to generate assembly for a file
src/core/UpdateChecker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/core/UpdateChecker.cpp.s
.PHONY : src/core/UpdateChecker.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ui/BroadcastWidget.obj: src/ui/BroadcastWidget.cpp.obj
.PHONY : src/ui/BroadcastWidget.obj

# target to build an object file
src/ui/BroadcastWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/BroadcastWidget.cpp.obj
.PHONY : src/ui/BroadcastWidget.cpp.obj

src/ui/BroadcastWidget.i: src/ui/BroadcastWidget.cpp.i
.PHONY : src/ui/BroadcastWidget.i

# target to preprocess a source file
src/ui/BroadcastWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/BroadcastWidget.cpp.i
.PHONY : src/ui/BroadcastWidget.cpp.i

src/ui/BroadcastWidget.s: src/ui/BroadcastWidget.cpp.s
.PHONY : src/ui/BroadcastWidget.s

# target to generate assembly for a file
src/ui/BroadcastWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/BroadcastWidget.cpp.s
.PHONY : src/ui/BroadcastWidget.cpp.s

src/ui/ChangelogDialog.obj: src/ui/ChangelogDialog.cpp.obj
.PHONY : src/ui/ChangelogDialog.obj

# target to build an object file
src/ui/ChangelogDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ChangelogDialog.cpp.obj
.PHONY : src/ui/ChangelogDialog.cpp.obj

src/ui/ChangelogDialog.i: src/ui/ChangelogDialog.cpp.i
.PHONY : src/ui/ChangelogDialog.i

# target to preprocess a source file
src/ui/ChangelogDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ChangelogDialog.cpp.i
.PHONY : src/ui/ChangelogDialog.cpp.i

src/ui/ChangelogDialog.s: src/ui/ChangelogDialog.cpp.s
.PHONY : src/ui/ChangelogDialog.s

# target to generate assembly for a file
src/ui/ChangelogDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ChangelogDialog.cpp.s
.PHONY : src/ui/ChangelogDialog.cpp.s

src/ui/FriendsWidget.obj: src/ui/FriendsWidget.cpp.obj
.PHONY : src/ui/FriendsWidget.obj

# target to build an object file
src/ui/FriendsWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/FriendsWidget.cpp.obj
.PHONY : src/ui/FriendsWidget.cpp.obj

src/ui/FriendsWidget.i: src/ui/FriendsWidget.cpp.i
.PHONY : src/ui/FriendsWidget.i

# target to preprocess a source file
src/ui/FriendsWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/FriendsWidget.cpp.i
.PHONY : src/ui/FriendsWidget.cpp.i

src/ui/FriendsWidget.s: src/ui/FriendsWidget.cpp.s
.PHONY : src/ui/FriendsWidget.s

# target to generate assembly for a file
src/ui/FriendsWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/FriendsWidget.cpp.s
.PHONY : src/ui/FriendsWidget.cpp.s

src/ui/GameCardWidget.obj: src/ui/GameCardWidget.cpp.obj
.PHONY : src/ui/GameCardWidget.obj

# target to build an object file
src/ui/GameCardWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/GameCardWidget.cpp.obj
.PHONY : src/ui/GameCardWidget.cpp.obj

src/ui/GameCardWidget.i: src/ui/GameCardWidget.cpp.i
.PHONY : src/ui/GameCardWidget.i

# target to preprocess a source file
src/ui/GameCardWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/GameCardWidget.cpp.i
.PHONY : src/ui/GameCardWidget.cpp.i

src/ui/GameCardWidget.s: src/ui/GameCardWidget.cpp.s
.PHONY : src/ui/GameCardWidget.s

# target to generate assembly for a file
src/ui/GameCardWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/GameCardWidget.cpp.s
.PHONY : src/ui/GameCardWidget.cpp.s

src/ui/InstallProgressDialog.obj: src/ui/InstallProgressDialog.cpp.obj
.PHONY : src/ui/InstallProgressDialog.obj

# target to build an object file
src/ui/InstallProgressDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/InstallProgressDialog.cpp.obj
.PHONY : src/ui/InstallProgressDialog.cpp.obj

src/ui/InstallProgressDialog.i: src/ui/InstallProgressDialog.cpp.i
.PHONY : src/ui/InstallProgressDialog.i

# target to preprocess a source file
src/ui/InstallProgressDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/InstallProgressDialog.cpp.i
.PHONY : src/ui/InstallProgressDialog.cpp.i

src/ui/InstallProgressDialog.s: src/ui/InstallProgressDialog.cpp.s
.PHONY : src/ui/InstallProgressDialog.s

# target to generate assembly for a file
src/ui/InstallProgressDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/InstallProgressDialog.cpp.s
.PHONY : src/ui/InstallProgressDialog.cpp.s

src/ui/LoginWidget.obj: src/ui/LoginWidget.cpp.obj
.PHONY : src/ui/LoginWidget.obj

# target to build an object file
src/ui/LoginWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/LoginWidget.cpp.obj
.PHONY : src/ui/LoginWidget.cpp.obj

src/ui/LoginWidget.i: src/ui/LoginWidget.cpp.i
.PHONY : src/ui/LoginWidget.i

# target to preprocess a source file
src/ui/LoginWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/LoginWidget.cpp.i
.PHONY : src/ui/LoginWidget.cpp.i

src/ui/LoginWidget.s: src/ui/LoginWidget.cpp.s
.PHONY : src/ui/LoginWidget.s

# target to generate assembly for a file
src/ui/LoginWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/LoginWidget.cpp.s
.PHONY : src/ui/LoginWidget.cpp.s

src/ui/MainWindow.obj: src/ui/MainWindow.cpp.obj
.PHONY : src/ui/MainWindow.obj

# target to build an object file
src/ui/MainWindow.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/MainWindow.cpp.obj
.PHONY : src/ui/MainWindow.cpp.obj

src/ui/MainWindow.i: src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.i

# target to preprocess a source file
src/ui/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/MainWindow.cpp.i
.PHONY : src/ui/MainWindow.cpp.i

src/ui/MainWindow.s: src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.s

# target to generate assembly for a file
src/ui/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/MainWindow.cpp.s
.PHONY : src/ui/MainWindow.cpp.s

src/ui/ManageDialog.obj: src/ui/ManageDialog.cpp.obj
.PHONY : src/ui/ManageDialog.obj

# target to build an object file
src/ui/ManageDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ManageDialog.cpp.obj
.PHONY : src/ui/ManageDialog.cpp.obj

src/ui/ManageDialog.i: src/ui/ManageDialog.cpp.i
.PHONY : src/ui/ManageDialog.i

# target to preprocess a source file
src/ui/ManageDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ManageDialog.cpp.i
.PHONY : src/ui/ManageDialog.cpp.i

src/ui/ManageDialog.s: src/ui/ManageDialog.cpp.s
.PHONY : src/ui/ManageDialog.s

# target to generate assembly for a file
src/ui/ManageDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ManageDialog.cpp.s
.PHONY : src/ui/ManageDialog.cpp.s

src/ui/ProfileWidget.obj: src/ui/ProfileWidget.cpp.obj
.PHONY : src/ui/ProfileWidget.obj

# target to build an object file
src/ui/ProfileWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ProfileWidget.cpp.obj
.PHONY : src/ui/ProfileWidget.cpp.obj

src/ui/ProfileWidget.i: src/ui/ProfileWidget.cpp.i
.PHONY : src/ui/ProfileWidget.i

# target to preprocess a source file
src/ui/ProfileWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ProfileWidget.cpp.i
.PHONY : src/ui/ProfileWidget.cpp.i

src/ui/ProfileWidget.s: src/ui/ProfileWidget.cpp.s
.PHONY : src/ui/ProfileWidget.s

# target to generate assembly for a file
src/ui/ProfileWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ProfileWidget.cpp.s
.PHONY : src/ui/ProfileWidget.cpp.s

src/ui/SettingsDialog.obj: src/ui/SettingsDialog.cpp.obj
.PHONY : src/ui/SettingsDialog.obj

# target to build an object file
src/ui/SettingsDialog.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/SettingsDialog.cpp.obj
.PHONY : src/ui/SettingsDialog.cpp.obj

src/ui/SettingsDialog.i: src/ui/SettingsDialog.cpp.i
.PHONY : src/ui/SettingsDialog.i

# target to preprocess a source file
src/ui/SettingsDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/SettingsDialog.cpp.i
.PHONY : src/ui/SettingsDialog.cpp.i

src/ui/SettingsDialog.s: src/ui/SettingsDialog.cpp.s
.PHONY : src/ui/SettingsDialog.s

# target to generate assembly for a file
src/ui/SettingsDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/SettingsDialog.cpp.s
.PHONY : src/ui/SettingsDialog.cpp.s

src/ui/StatsWidget.obj: src/ui/StatsWidget.cpp.obj
.PHONY : src/ui/StatsWidget.obj

# target to build an object file
src/ui/StatsWidget.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/StatsWidget.cpp.obj
.PHONY : src/ui/StatsWidget.cpp.obj

src/ui/StatsWidget.i: src/ui/StatsWidget.cpp.i
.PHONY : src/ui/StatsWidget.i

# target to preprocess a source file
src/ui/StatsWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/StatsWidget.cpp.i
.PHONY : src/ui/StatsWidget.cpp.i

src/ui/StatsWidget.s: src/ui/StatsWidget.cpp.s
.PHONY : src/ui/StatsWidget.s

# target to generate assembly for a file
src/ui/StatsWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/StatsWidget.cpp.s
.PHONY : src/ui/StatsWidget.cpp.s

src/ui/ToggleSwitch.obj: src/ui/ToggleSwitch.cpp.obj
.PHONY : src/ui/ToggleSwitch.obj

# target to build an object file
src/ui/ToggleSwitch.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ToggleSwitch.cpp.obj
.PHONY : src/ui/ToggleSwitch.cpp.obj

src/ui/ToggleSwitch.i: src/ui/ToggleSwitch.cpp.i
.PHONY : src/ui/ToggleSwitch.i

# target to preprocess a source file
src/ui/ToggleSwitch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ToggleSwitch.cpp.i
.PHONY : src/ui/ToggleSwitch.cpp.i

src/ui/ToggleSwitch.s: src/ui/ToggleSwitch.cpp.s
.PHONY : src/ui/ToggleSwitch.s

# target to generate assembly for a file
src/ui/ToggleSwitch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/ToggleSwitch.cpp.s
.PHONY : src/ui/ToggleSwitch.cpp.s

src/ui/TrayController.obj: src/ui/TrayController.cpp.obj
.PHONY : src/ui/TrayController.obj

# target to build an object file
src/ui/TrayController.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/TrayController.cpp.obj
.PHONY : src/ui/TrayController.cpp.obj

src/ui/TrayController.i: src/ui/TrayController.cpp.i
.PHONY : src/ui/TrayController.i

# target to preprocess a source file
src/ui/TrayController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/TrayController.cpp.i
.PHONY : src/ui/TrayController.cpp.i

src/ui/TrayController.s: src/ui/TrayController.cpp.s
.PHONY : src/ui/TrayController.s

# target to generate assembly for a file
src/ui/TrayController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ETALauncher.dir\build.make CMakeFiles/ETALauncher.dir/src/ui/TrayController.cpp.s
.PHONY : src/ui/TrayController.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ETALauncher_autogen
	@echo ... ETALauncher_autogen_timestamp_deps
	@echo ... ETALauncher
	@echo ... ETALauncher_autogen/EWIEGA46WW/qrc_resources.obj
	@echo ... ETALauncher_autogen/EWIEGA46WW/qrc_resources.i
	@echo ... ETALauncher_autogen/EWIEGA46WW/qrc_resources.s
	@echo ... ETALauncher_autogen/mocs_compilation.obj
	@echo ... ETALauncher_autogen/mocs_compilation.i
	@echo ... ETALauncher_autogen/mocs_compilation.s
	@echo ... src/core/AuthManager.obj
	@echo ... src/core/AuthManager.i
	@echo ... src/core/AuthManager.s
	@echo ... src/core/BroadcastManager.obj
	@echo ... src/core/BroadcastManager.i
	@echo ... src/core/BroadcastManager.s
	@echo ... src/core/Config.obj
	@echo ... src/core/Config.i
	@echo ... src/core/Config.s
	@echo ... src/core/FirestoreClient.obj
	@echo ... src/core/FirestoreClient.i
	@echo ... src/core/FirestoreClient.s
	@echo ... src/core/FriendsManager.obj
	@echo ... src/core/FriendsManager.i
	@echo ... src/core/FriendsManager.s
	@echo ... src/core/GameManager.obj
	@echo ... src/core/GameManager.i
	@echo ... src/core/GameManager.s
	@echo ... src/core/GitCloner.obj
	@echo ... src/core/GitCloner.i
	@echo ... src/core/GitCloner.s
	@echo ... src/core/I18n.obj
	@echo ... src/core/I18n.i
	@echo ... src/core/I18n.s
	@echo ... src/core/PlayStats.obj
	@echo ... src/core/PlayStats.i
	@echo ... src/core/PlayStats.s
	@echo ... src/core/PresenceManager.obj
	@echo ... src/core/PresenceManager.i
	@echo ... src/core/PresenceManager.s
	@echo ... src/core/RepoUpdater.obj
	@echo ... src/core/RepoUpdater.i
	@echo ... src/core/RepoUpdater.s
	@echo ... src/core/SelfUpdater.obj
	@echo ... src/core/SelfUpdater.i
	@echo ... src/core/SelfUpdater.s
	@echo ... src/core/SessionStore.obj
	@echo ... src/core/SessionStore.i
	@echo ... src/core/SessionStore.s
	@echo ... src/core/ShortcutManager.obj
	@echo ... src/core/ShortcutManager.i
	@echo ... src/core/ShortcutManager.s
	@echo ... src/core/ThemeManager.obj
	@echo ... src/core/ThemeManager.i
	@echo ... src/core/ThemeManager.s
	@echo ... src/core/Translations.obj
	@echo ... src/core/Translations.i
	@echo ... src/core/Translations.s
	@echo ... src/core/UpdateChecker.obj
	@echo ... src/core/UpdateChecker.i
	@echo ... src/core/UpdateChecker.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/ui/BroadcastWidget.obj
	@echo ... src/ui/BroadcastWidget.i
	@echo ... src/ui/BroadcastWidget.s
	@echo ... src/ui/ChangelogDialog.obj
	@echo ... src/ui/ChangelogDialog.i
	@echo ... src/ui/ChangelogDialog.s
	@echo ... src/ui/FriendsWidget.obj
	@echo ... src/ui/FriendsWidget.i
	@echo ... src/ui/FriendsWidget.s
	@echo ... src/ui/GameCardWidget.obj
	@echo ... src/ui/GameCardWidget.i
	@echo ... src/ui/GameCardWidget.s
	@echo ... src/ui/InstallProgressDialog.obj
	@echo ... src/ui/InstallProgressDialog.i
	@echo ... src/ui/InstallProgressDialog.s
	@echo ... src/ui/LoginWidget.obj
	@echo ... src/ui/LoginWidget.i
	@echo ... src/ui/LoginWidget.s
	@echo ... src/ui/MainWindow.obj
	@echo ... src/ui/MainWindow.i
	@echo ... src/ui/MainWindow.s
	@echo ... src/ui/ManageDialog.obj
	@echo ... src/ui/ManageDialog.i
	@echo ... src/ui/ManageDialog.s
	@echo ... src/ui/ProfileWidget.obj
	@echo ... src/ui/ProfileWidget.i
	@echo ... src/ui/ProfileWidget.s
	@echo ... src/ui/SettingsDialog.obj
	@echo ... src/ui/SettingsDialog.i
	@echo ... src/ui/SettingsDialog.s
	@echo ... src/ui/StatsWidget.obj
	@echo ... src/ui/StatsWidget.i
	@echo ... src/ui/StatsWidget.s
	@echo ... src/ui/ToggleSwitch.obj
	@echo ... src/ui/ToggleSwitch.i
	@echo ... src/ui/ToggleSwitch.s
	@echo ... src/ui/TrayController.obj
	@echo ... src/ui/TrayController.i
	@echo ... src/ui/TrayController.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

